# Generated by Django 5.0.14 on 2025-05-24 20:16

import datetime
import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'مدرک تحصیلی',
                'verbose_name_plural': 'مدارک تحصیلی',
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام لایسنس')),
                ('max_users', models.PositiveIntegerField(default=1, verbose_name='حداکثر تعداد کاربران')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت')),
                ('duration_days', models.PositiveIntegerField(default=365, verbose_name='مدت اعتبار (روز)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'لایسنس',
                'verbose_name_plural': 'لایسنس\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام تخصص')),
            ],
            options={
                'verbose_name': 'تخصص',
                'verbose_name_plural': 'تخصص\u200cها',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('login_datetime', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(default=datetime.date.today, verbose_name='تاریخ پایان')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('role', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.role')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
        ),
        migrations.CreateModel(
            name='DoctorFinancialDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('lab_expense_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('material_expense_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('is_activate', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('avatar', models.ImageField(default='default.jpg', upload_to=users.models.user_directory_path)),
                ('signature', models.ImageField(default='signature.jpg', upload_to=users.models.user_directory_path)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('personal_number', models.CharField(default=users.models.generate_personal_number, max_length=50)),
                ('medical_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('national_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('sex', models.BooleanField(default=True)),
                ('is_married', models.BooleanField(default=False)),
                ('birth_date', models.DateField(default=datetime.date.today, verbose_name='تاریخ تولد')),
                ('birthplace', models.CharField(blank=True, max_length=100, null=True)),
                ('work_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='درصد کارکرد پزشک')),
                ('lab_expense_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='درصد هزینه لابراتوار')),
                ('material_expense_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='درصد هزینه مواد')),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='درصد مالیات')),
                ('education', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.education')),
                ('license', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.license')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.role')),
                ('specialty', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.specialty')),
            ],
        ),
        migrations.CreateModel(
            name='UserLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(verbose_name='تاریخ پایان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.license', verbose_name='لایسنس')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'لایسنس کاربر',
                'verbose_name_plural': 'لایسنس\u200cهای کاربران',
            },
        ),
    ]
