# Generated by Django 5.0.14 on 2025-05-25 21:38

import django.db.models.deletion
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_role_options_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonnelCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=10, unique=True, verbose_name='شماره کارت')),
                ('avatar', models.ImageField(upload_to=users.models.user_directory_path, verbose_name='عکس پرسنلی')),
                ('signature', models.ImageField(upload_to=users.models.user_directory_path, verbose_name='امضا')),
                ('qr_code', models.ImageField(blank=True, upload_to=users.models.user_directory_path, verbose_name='کد QR')),
                ('issue_date', models.DateField(auto_now_add=True, verbose_name='تاریخ صدور')),
                ('expiry_date', models.DateField(verbose_name='تاریخ انقضا')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('last_entry', models.DateTimeField(blank=True, null=True, verbose_name='آخرین ورود')),
                ('last_exit', models.DateTimeField(blank=True, null=True, verbose_name='آخرین خروج')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personnel_card', to='users.profile')),
            ],
            options={
                'verbose_name': 'کارت پرسنلی',
                'verbose_name_plural': 'کارت\u200cهای پرسنلی',
            },
        ),
    ]
