# Generated by Django 5.0.14 on 2025-05-25 21:39

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_personnelcard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='signature',
        ),
        migrations.AlterField(
            model_name='personnelcard',
            name='avatar',
            field=models.ImageField(default='default.jpg', upload_to=users.models.user_directory_path, verbose_name='عکس پرسنلی'),
        ),
        migrations.AlterField(
            model_name='personnelcard',
            name='signature',
            field=models.ImageField(default='signature.jpg', upload_to=users.models.user_directory_path, verbose_name='امضا'),
        ),
    ]
