# Generated by Django 5.0.14 on 2025-05-26 19:49

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_profile_avatar_remove_profile_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnelcard',
            name='card_image',
            field=models.ImageField(blank=True, upload_to=users.models.user_directory_path, verbose_name='تصویر کارت'),
        ),
    ]
