# Generated by Django 5.0.14 on 2025-07-06 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

   
    operations = [
        migrations.CreateModel(
            name='InstallmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ کل')),
                ('down_payment', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='پیش پرداخت')),
                ('installment_count', models.PositiveIntegerField(verbose_name='تعداد اقساط')),
                ('installment_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ هر قسط')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع اقساط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'طرح اقساط',
                'verbose_name_plural': 'طرح\u200cهای اقساط',
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ')),
                ('due_date', models.DateField(verbose_name='تاریخ سررسید')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='Treatment.installmentplan', verbose_name='طرح اقساط')),
            ],
            options={
                'verbose_name': 'قسط',
                'verbose_name_plural': 'اقساط',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_date', models.DateField(verbose_name='تاریخ درمان')),
                ('next_visit_date', models.DateField(blank=True, null=True, verbose_name='تاریخ مراجعه بعدی')),
                ('treatment_areas', models.CharField(max_length=200, verbose_name='نواحی درمان')),
                ('area_type', models.CharField(default='teeth', max_length=50, verbose_name='نوع ناحیه')),
                ('general_fee', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='تعرفه عمومی')),
                ('special_fee', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='تعرفه تخصصی')),
                ('discount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='تخفیف')),
                ('material_cost', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='هزینه مواد')),
                ('lab_cost', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='هزینه لابراتوار')),
                ('payable_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ قابل پرداخت')),
                ('insurance_percentage', models.PositiveIntegerField(default=0, verbose_name='درصد بیمه')),
                ('insurance_sent', models.BooleanField(default=False, verbose_name='ارسال شده به بیمه')),
                ('insurance_paid', models.BooleanField(default=False, verbose_name='از بیمه مبلغ دریافت شده')),
                ('is_completed', models.BooleanField(default=False, verbose_name='درمان انجام شده')),
                ('is_treatment_plan', models.BooleanField(default=False, verbose_name='طرح درمان')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('assistant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatments_as_assistant', to=settings.AUTH_USER_MODEL, verbose_name='دستیار پزشک')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatments_as_doctor', to=settings.AUTH_USER_MODEL, verbose_name='پزشک معالج')),
                ('insurance_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Patient.insuranceprovider', verbose_name='بیمه\u200cگر')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='Patient.patientrecord', verbose_name='بیمار')),
                ('treatment_detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatments', to='Patient.treatmentdetail', verbose_name='شرح درمان')),
                ('treatment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatments', to='Patient.treatmenttype', verbose_name='نوع درمان')),
            ],
            options={
                'verbose_name': 'درمان',
                'verbose_name_plural': 'درمان\u200cها',
                'ordering': ['-treatment_date'],
            },
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='treatment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='installment_plan', to='Treatment.treatment', verbose_name='درمان'),
        ),
        migrations.CreateModel(
            name='TreatmentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ')),
                ('payment_date', models.DateField(verbose_name='تاریخ پرداخت')),
                ('payment_method', models.CharField(max_length=50, verbose_name='روش پرداخت')),
                ('check_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره چک')),
                ('check_date', models.DateField(blank=True, null=True, verbose_name='تاریخ چک')),
                ('check_bank', models.CharField(blank=True, max_length=100, null=True, verbose_name='بانک چک')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='Treatment.treatment', verbose_name='درمان')),
            ],
            options={
                'verbose_name': 'پرداخت درمان',
                'verbose_name_plural': 'پرداخت\u200cهای درمان',
                'ordering': ['-payment_date'],
            },
        ),
    ]
