# Generated by Django 5.0.14 on 2025-07-09 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Treatment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installmentplan',
            name='treatment',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='assistant',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='insurance_provider',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='treatment_detail',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='treatment_type',
        ),
        migrations.RemoveField(
            model_name='treatmentpayment',
            name='treatment',
        ),
        migrations.DeleteModel(
            name='Installment',
        ),
        migrations.DeleteModel(
            name='InstallmentPlan',
        ),
        migrations.DeleteModel(
            name='Treatment',
        ),
        migrations.DeleteModel(
            name='TreatmentPayment',
        ),
    ]
