# Generated by Django 5.0.14 on 2025-06-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_duration', models.IntegerField(choices=[(15, '15 دقیقه'), (30, '30 دقیقه'), (45, '45 دقیقه'), (60, '60 دقیقه')], default=30, verbose_name='مدت زمان ویزیت')),
                ('allow_past_edit', models.BooleanField(default=False, verbose_name='امکان ویرایش روزهای گذشته')),
                ('show_patient_info', models.BooleanField(default=True, verbose_name='نمایش اطلاعات بیمار')),
                ('calendar_start_time', models.TimeField(default='08:00', verbose_name='ساعت شروع تقویم')),
                ('calendar_end_time', models.TimeField(default='20:00', verbose_name='ساعت پایان تقویم')),
                ('normal_appointment_color', models.CharField(default='#d4edda', max_length=7, verbose_name='رنگ نوبت عادی')),
                ('emergency_appointment_color', models.CharField(default='#f8d7da', max_length=7, verbose_name='رنگ نوبت اورژانسی')),
                ('pending_appointment_color', models.CharField(default='#fff3cd', max_length=7, verbose_name='رنگ نوبت در انتظار')),
            ],
            options={
                'verbose_name': 'تنظیمات نوبت\u200cدهی',
                'verbose_name_plural': 'تنظیمات نوبت\u200cدهی',
            },
        ),
    ]
