# Generated by Django 5.0.14 on 2025-06-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentsettings',
            name='calendar_end_time',
            field=models.TimeField(default='11:59', verbose_name='ساعت پایان تقویم'),
        ),
        migrations.AlterField(
            model_name='appointmentsettings',
            name='calendar_start_time',
            field=models.TimeField(default='12:00', verbose_name='ساعت شروع تقویم'),
        ),
        migrations.AlterField(
            model_name='appointmentsettings',
            name='emergency_appointment_color',
            field=models.CharField(default='#ed989f', max_length=7, verbose_name='رنگ نوبت اورژانسی'),
        ),
    ]
