# Generated by Django 5.0.14 on 2025-07-17 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_appointmentsettings_calendar_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(default='کلینیک دندانپزشکی', max_length=200, verbose_name='نام کلینیک/مطب')),
                ('clinic_logo', models.ImageField(blank=True, null=True, upload_to='settings/logo/', verbose_name='لوگوی کلینیک')),
                ('phone_number1', models.CharField(blank=True, max_length=20, verbose_name='شماره تلفن اصلی')),
                ('phone_number2', models.CharField(blank=True, max_length=20, verbose_name='شماره تلفن دوم (اختیاری)')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='آدرس ایمیل')),
                ('website', models.URLField(blank=True, verbose_name='وب\u200cسایت')),
                ('province', models.CharField(blank=True, max_length=100, verbose_name='استان')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='شهر')),
                ('address', models.TextField(blank=True, verbose_name='آدرس دقیق')),
                ('currency_unit', models.CharField(default='ریال', max_length=20, verbose_name='واحد پولی')),
                ('notification_days_before', models.PositiveIntegerField(default=3, help_text='یادآوری چک\u200cها و اقساط، چند روز قبل از سررسید نمایش داده شوند؟', verbose_name='تعداد روز قبل برای نمایش یادآوری')),
            ],
            options={
                'verbose_name': 'تنظیمات کلینیک',
                'verbose_name_plural': 'تنظیمات کلینیک',
            },
        ),
    ]
