# Generated by Django 5.0.14 on 2025-07-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_clinicsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicsetting',
            name='clinic_name',
            field=models.CharField(default='کلینیک ', max_length=200, verbose_name='نام کلینیک/مطب'),
        ),
    ]
