# Generated by Django 5.0.14 on 2025-08-02 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_add_default_data'),
        ('users', '0006_personnelcard_card_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='media/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_warehouses', to='users.profile', verbose_name='مدیر انبار'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode__isnull', False)), fields=('barcode',), name='unique_barcode_if_not_null'),
        ),
    ]
