# Generated by Django 5.0.14 on 2025-08-04 20:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_item_image_alter_warehouse_manager_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('message', models.TextField(verbose_name='پیام')),
                ('notification_type', models.CharField(choices=[('LOW_STOCK', 'موجودی کم'), ('OUT_OF_STOCK', 'اتمام موجودی'), ('EXPIRY_WARNING', 'هشدار انقضا'), ('EXPIRED_ITEM', 'کالای منقضی'), ('STOCK_ENTRY', 'ورودی انبار'), ('STOCK_EXIT', 'خروجی انبار'), ('STOCK_TRANSFER', 'انتقال انبار'), ('SYSTEM_ALERT', 'هشدار سیستم'), ('USER_ACTION', 'عمل کاربر'), ('INVENTORY_ADJUSTMENT', 'تعدیل موجودی'), ('BATCH_EXPIRY', 'انقضای بچ'), ('WAREHOUSE_ALERT', 'هشدار انبار')], max_length=30, verbose_name='نوع اعلان')),
                ('priority', models.CharField(choices=[('LOW', 'کم'), ('MEDIUM', 'متوسط'), ('HIGH', 'بالا'), ('CRITICAL', 'بحرانی')], default='MEDIUM', max_length=10, verbose_name='اولویت')),
                ('status', models.CharField(choices=[('UNREAD', 'خوانده نشده'), ('READ', 'خوانده شده'), ('ARCHIVED', 'آرشیو شده'), ('DISMISSED', 'نادیده گرفته شده')], default='UNREAD', max_length=15, verbose_name='وضعیت')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='متادیتا')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ خواندن')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('action_url', models.URLField(blank=True, null=True, verbose_name='لینک عمل')),
                ('action_text', models.CharField(blank=True, max_length=50, null=True, verbose_name='متن عمل')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='گیرنده')),
                ('related_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.stockbatch', verbose_name='بچ مرتبط')),
                ('related_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.item', verbose_name='کالای مرتبط')),
                ('related_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse', verbose_name='انبار مرتبط')),
            ],
            options={
                'verbose_name': 'اعلان',
                'verbose_name_plural': 'اعلانات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('BROWSER', 'مرورگر'), ('EMAIL', 'ایمیل'), ('SMS', 'پیامک'), ('PUSH', 'Push Notification')], max_length=10, verbose_name='روش ارسال')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار'), ('SENT', 'ارسال شده'), ('DELIVERED', 'تحویل شده'), ('FAILED', 'ناموفق'), ('BOUNCED', 'برگشت خورده')], default='PENDING', max_length=15, verbose_name='وضعیت ارسال')),
                ('recipient_address', models.CharField(max_length=255, verbose_name='آدرس گیرنده')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تحویل')),
                ('error_message', models.TextField(blank=True, verbose_name='پیام خطا')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='inventory.notification', verbose_name='اعلان')),
            ],
            options={
                'verbose_name': 'تحویل اعلان',
                'verbose_name_plural': 'تحویل اعلانات',
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='اعلان ایمیل')),
                ('sms_notifications', models.BooleanField(default=False, verbose_name='اعلان پیامک')),
                ('browser_notifications', models.BooleanField(default=True, verbose_name='اعلان مرورگر')),
                ('low_stock_alerts', models.BooleanField(default=True, verbose_name='هشدار موجودی کم')),
                ('out_of_stock_alerts', models.BooleanField(default=True, verbose_name='هشدار اتمام موجودی')),
                ('expiry_alerts', models.BooleanField(default=True, verbose_name='هشدار انقضا')),
                ('entry_notifications', models.BooleanField(default=False, verbose_name='اعلان ورودی')),
                ('exit_notifications', models.BooleanField(default=False, verbose_name='اعلان خروجی')),
                ('transfer_notifications', models.BooleanField(default=True, verbose_name='اعلان انتقال')),
                ('quiet_hours_start', models.TimeField(blank=True, null=True, verbose_name='شروع ساعات سکوت')),
                ('quiet_hours_end', models.TimeField(blank=True, null=True, verbose_name='پایان ساعات سکوت')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('watched_items', models.ManyToManyField(blank=True, to='inventory.item', verbose_name='کالاهای تحت نظر')),
                ('watched_warehouses', models.ManyToManyField(blank=True, to='inventory.warehouse', verbose_name='انبارهای تحت نظر')),
            ],
            options={
                'verbose_name': 'تنظیمات اعلان',
                'verbose_name_plural': 'تنظیمات اعلانات',
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'status', '-created_at'], name='inventory_n_recipie_fdae43_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type', '-created_at'], name='inventory_n_notific_f91955_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['priority', '-created_at'], name='inventory_n_priorit_7355c0_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['status', '-created_at'], name='inventory_n_status_8ee099_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['related_item', '-created_at'], name='inventory_n_related_085974_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['related_warehouse', '-created_at'], name='inventory_n_related_645b6b_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['expires_at'], name='inventory_n_expires_36fdd7_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['notification', 'method'], name='inventory_n_notific_2fb442_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['status', '-created_at'], name='inventory_n_status_2d2764_idx'),
        ),
    ]
