# Generated by Django 5.0.14 on 2025-08-07 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_notification_notificationdelivery_and_more'),
        ('users', '0006_personnelcard_card_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_global',
            field=models.BooleanField(default=False, help_text='آیا این اعلان برای همه کاربران قابل مشاهده است؟'),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_notifications', to='users.role'),
        ),
    ]
