# Generated by Django 5.0.14 on 2025-08-08 00:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_notification_is_admin_only_and_more'),
        ('users', '0006_personnelcard_card_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='inventory_n_recipie_fdae43_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='inventory_n_notific_f91955_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='inventory_n_priorit_7355c0_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='inventory_n_status_8ee099_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='inventory_n_related_085974_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='inventory_n_related_645b6b_idx',
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'status', 'created_at'], name='inventory_n_recipie_4e459a_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type', 'created_at'], name='inventory_n_notific_7f8145_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['priority', 'created_at'], name='inventory_n_priorit_b5ac8d_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['status', 'created_at'], name='inventory_n_status_b440fc_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['related_item', 'created_at'], name='inventory_n_related_f834f4_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['related_warehouse', 'created_at'], name='inventory_n_related_bb53ff_idx'),
        ),
    ]
