# Generated by Django 5.0.14 on 2025-07-18 17:17

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models

# تابع ایجاد انواع تخفیف پیش‌فرض
def create_default_discount_types(apps, schema_editor):
    # دریافت مدل DiscountType
    DiscountType = apps.get_model('Patient', 'DiscountType')
    
    # ایجاد انواع تخفیف پیش‌فرض
    DiscountType.objects.create(
        name='تخفیف پزشک',
        doctor_percentage=100,
        clinic_percentage=0,
        is_active=True
    )
    
    DiscountType.objects.create(
        name='تخفیف کلینیک',
        doctor_percentage=0,
        clinic_percentage=100,
        is_active=True
    )
    
    DiscountType.objects.create(
        name='تخفیف پزشک و کلینیک',
        doctor_percentage=50,
        clinic_percentage=50,
        is_active=True
    )


# تابع حذف انواع تخفیف پیش‌فرض (برای rollback)
def delete_default_discount_types(apps, schema_editor):
    # دریافت مدل DiscountType
    DiscountType = apps.get_model('Patient', 'DiscountType')
    
    # حذف انواع تخفیف پیش‌فرض
    DiscountType.objects.filter(
        name__in=['تخفیف پزشک', 'تخفیف کلینیک', 'تخفیف پزشک و کلینیک']
    ).delete()


# تابع ایجاد انواع بیمه پیش‌فرض
def create_default_insurance_types(apps, schema_editor):
    # دریافت مدل InsuranceType
    InsuranceType = apps.get_model('Patient', 'InsuranceType')
    
    # ایجاد انواع بیمه پیش‌فرض
    InsuranceType.objects.create(
        name='آزاد',
        code='FREE',
        description='بیمار بدون بیمه'
    )
    
    InsuranceType.objects.create(
        name='بیمه درصدی',
        code='PERCENTAGE',
        description='بیمه با پوشش درصدی از هزینه‌ها'
    )
    
    InsuranceType.objects.create(
        name='بیمه تعرفه‌ای',
        code='TARIFF',
        description='بیمه با تعرفه مشخص برای هر خدمت'
    )
    
    InsuranceType.objects.create(
        name='بیمه کلی',
        code='GENERAL',
        description='بیمه با پوشش کلی خدمات'
    )


# تابع حذف انواع بیمه پیش‌فرض (برای rollback)
def delete_default_insurance_types(apps, schema_editor):
    # دریافت مدل InsuranceType
    InsuranceType = apps.get_model('Patient', 'InsuranceType')
    
    # حذف انواع بیمه پیش‌فرض
    InsuranceType.objects.filter(
        code__in=['FREE', 'PERCENTAGE', 'TARIFF', 'GENERAL']
    ).delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_personnelcard_card_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام نوع تخفیف')),
                ('doctor_percentage', models.IntegerField(default=0, verbose_name='درصد سهم پزشک')),
                ('clinic_percentage', models.IntegerField(default=0, verbose_name='درصد سهم کلینیک')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'نوع تخفیف',
                'verbose_name_plural': 'انواع تخفیف',
            },
        ),
        migrations.CreateModel(
            name='InstallmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ کل')),
                ('down_payment', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='پیش پرداخت')),
                ('installment_count', models.PositiveIntegerField(verbose_name='تعداد اقساط')),
                ('installment_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ هر قسط')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع اقساط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'طرح اقساط',
                'verbose_name_plural': 'طرح\u200cهای اقساط',
            },
        ),
        migrations.CreateModel(
            name='InsuranceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام نوع بیمه')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='کد نوع بیمه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'نوع بیمه',
                'verbose_name_plural': 'انواع بیمه',
            },
        ),
        migrations.CreateModel(
            name='TreatmentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='شرح درمان')),
                ('international_code', models.CharField(db_index=True, max_length=50, verbose_name='کد بین\u200cالمللی')),
                ('public_tariff', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='تعرفه عمومی')),
                ('special_tariff', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='تعرفه تخصصی')),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='نوع درمان')),
            ],
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ')),
                ('due_date', models.DateField(verbose_name='تاریخ سررسید')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('is_reminder_seen', models.BooleanField(default=False, verbose_name='یادآوری دیده شده؟')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='Patient.installmentplan', verbose_name='طرح اقساط')),
            ],
            options={
                'verbose_name': 'قسط',
                'verbose_name_plural': 'اقساط',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام بیمه\u200cگر')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='کد بیمه\u200cگر')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='insurance_logos/', verbose_name='لوگو')),
                ('contact_info', models.CharField(blank=True, max_length=200, null=True, verbose_name='اطلاعات تماس')),
                ('website', models.URLField(blank=True, null=True, verbose_name='وب\u200cسایت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('insurance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='Patient.insurancetype', verbose_name='نوع بیمه')),
            ],
            options={
                'verbose_name': 'بیمه\u200cگر',
                'verbose_name_plural': 'بیمه\u200cگران',
            },
        ),
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_num', models.CharField(max_length=50, unique=True, verbose_name='شماره پرونده')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('family', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('national_code', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='کد ملی')),
                ('name_of_father', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام پدر')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('contant_info', models.CharField(blank=True, max_length=150, null=True, verbose_name='تلفن تماس')),
                ('emergency_contact', models.CharField(blank=True, max_length=150, null=True, verbose_name='شماره اضطراری')),
                ('family_number', models.CharField(blank=True, max_length=150, null=True, verbose_name='تلفن سرپرست')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('sex', models.BooleanField(default=True, verbose_name='جنسیت')),
                ('occupation', models.CharField(blank=True, max_length=100, null=True, verbose_name='شغل')),
                ('blood_type', models.CharField(blank=True, max_length=5, null=True, verbose_name='گروه خونی')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='قد')),
                ('weight', models.PositiveIntegerField(blank=True, null=True, verbose_name='وزن')),
                ('medications_info', models.TextField(blank=True, null=True, verbose_name='سابقه بیماری\u200cهای خاص')),
                ('allergy', models.TextField(blank=True, null=True, verbose_name='حساسیت\u200cهای دارویی یا غذایی')),
                ('medicine_use', models.TextField(blank=True, null=True, verbose_name='داروهای مصرفی فعلی')),
                ('afraid_of_dental', models.CharField(blank=True, max_length=20, null=True, verbose_name='میزان ترس از دندانپزشکی')),
                ('addiction_to_alcohol', models.BooleanField(default=False, verbose_name='اعتیاد')),
                ('has_heart_disease', models.BooleanField(default=False, verbose_name='بیماری قلبی')),
                ('has_diabetes', models.BooleanField(default=False, verbose_name='دیابت')),
                ('has_blood_pressure', models.BooleanField(default=False, verbose_name='فشار خون')),
                ('has_hepatitis', models.BooleanField(default=False, verbose_name='هپاتیت')),
                ('is_pregnant', models.BooleanField(default=False, verbose_name='بارداری')),
                ('pregnancy_month', models.PositiveIntegerField(blank=True, null=True, verbose_name='ماه بارداری')),
                ('insurance', models.CharField(blank=True, max_length=100, null=True, verbose_name='بیمه')),
                ('insurance_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع بیمه')),
                ('insurance_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره بیمه')),
                ('insurance_expiry_date', models.DateField(blank=True, null=True, verbose_name='تاریخ انقضای بیمه')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='دسته بندی')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='رنگ')),
                ('status', models.CharField(blank=True, max_length=100, null=True, verbose_name='وضعیت')),
                ('introducer', models.CharField(blank=True, max_length=100, null=True, verbose_name='معرف')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('profile_picture', models.ImageField(blank=True, default='img/logo.png', null=True, upload_to='patient_profiles/', verbose_name='تصویر پروفایل')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('last_visit_date', models.DateField(blank=True, null=True, verbose_name='تاریخ آخرین مراجعه')),
                ('next_visit_date', models.DateField(blank=True, null=True, verbose_name='تاریخ مراجعه بعدی')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین بروزرسانی')),
                ('marital_status', models.CharField(blank=True, max_length=20, null=True, verbose_name='وضعیت تاهل')),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_records', to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_records', to=settings.AUTH_USER_MODEL, verbose_name='بروزرسانی کننده')),
            ],
            options={
                'verbose_name': 'پرونده بیمار',
                'verbose_name_plural': 'پرونده\u200cهای بیماران',
                'ordering': ['-create_date'],
            },
        ),
        migrations.CreateModel(
            name='PatientInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_number', models.CharField(max_length=50, verbose_name='شماره بیمه')),
                ('expiry_date', models.DateField(verbose_name='تاریخ انقضا')),
                ('coverage_percentage', models.PositiveIntegerField(blank=True, null=True, verbose_name='درصد پوشش')),
                ('is_primary', models.BooleanField(default=False, verbose_name='بیمه اصلی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('insurance_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient.insuranceprovider', verbose_name='بیمه\u200cگر')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to='Patient.patientrecord', verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'بیمه بیمار',
                'verbose_name_plural': 'بیمه\u200cهای بیماران',
            },
        ),
        migrations.CreateModel(
            name='PatientCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=20, unique=True, verbose_name='شماره کارت')),
                ('issue_date', models.DateField(auto_now_add=True, verbose_name='تاریخ صدور')),
                ('expiry_date', models.DateField(verbose_name='تاریخ انقضا')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='امضا')),
                ('barcode', models.ImageField(blank=True, upload_to='barcodes/', verbose_name='بارکد')),
                ('qr_code', models.ImageField(blank=True, upload_to='qrcodes/', verbose_name='کیوآر کد')),
                ('card_image', models.ImageField(blank=True, upload_to='patient_cards/', verbose_name='تصویر کارت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_card', to='Patient.patientrecord')),
            ],
            options={
                'verbose_name': 'کارت بیمار',
                'verbose_name_plural': 'کارت\u200cهای بیماران',
            },
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=200, verbose_name='نام بیماری')),
                ('diagnosis_date', models.DateField(verbose_name='تاریخ تشخیص')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_histories', to='Patient.patientrecord', verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'سابقه پزشکی',
                'verbose_name_plural': 'سوابق پزشکی',
                'ordering': ['-diagnosis_date'],
            },
        ),
        migrations.CreateModel(
            name='DentalProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_date', models.DateField(verbose_name='تاریخ درمان')),
                ('tooth_number', models.CharField(max_length=10, verbose_name='شماره دندان')),
                ('procedure_type', models.CharField(max_length=100, verbose_name='نوع درمان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('cost', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='هزینه')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='انجام دهنده')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dental_procedures', to='Patient.patientrecord', verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'درمان دندانپزشکی',
                'verbose_name_plural': 'درمان\u200cهای دندانپزشکی',
                'ordering': ['-procedure_date'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='تاریخ و ساعت')),
                ('reason', models.CharField(max_length=200, verbose_name='علت مراجعه')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('confirmed', 'تایید شده'), ('cancelled', 'لغو شده'), ('completed', 'انجام شده')], default='pending', max_length=50, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='پزشک')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='Patient.patientrecord', verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'نوبت',
                'verbose_name_plural': 'نوبت\u200cها',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('medications', models.TextField(verbose_name='داروها')),
                ('instructions', models.TextField(verbose_name='دستورات مصرف')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='Patient.patientrecord', verbose_name='بیمار')),
                ('prescribed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تجویز کننده')),
            ],
            options={
                'verbose_name': 'نسخه',
                'verbose_name_plural': 'نسخه\u200cها',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PreviousTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=255, verbose_name='نام پزشک')),
                ('visit_date', models.DateField(verbose_name='تاریخ مراجعه')),
                ('description', models.TextField(verbose_name='شرح درمان')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_treatments', to='Patient.patientrecord')),
            ],
            options={
                'verbose_name': 'سابقه درمان قبلی',
                'verbose_name_plural': 'سوابق درمان قبلی',
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_date', models.DateField(verbose_name='تاریخ درمان')),
                ('next_visit_date', models.DateField(blank=True, null=True, verbose_name='تاریخ مراجعه بعدی')),
                ('treatment_areas', models.CharField(max_length=200, verbose_name='نواحی درمان')),
                ('area_type', models.CharField(default='teeth', max_length=50, verbose_name='نوع ناحیه')),
                ('general_fee', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='تعرفه عمومی')),
                ('special_fee', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='تعرفه تخصصی')),
                ('discount', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='مبلغ تخفیف')),
                ('material_cost', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='هزینه مواد')),
                ('lab_cost', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='هزینه لابراتوار')),
                ('payable_amount', models.DecimalField(decimal_places=0, default=Decimal('0.00'), max_digits=12, verbose_name='مبلغ قابل پرداخت')),
                ('insurance_percentage', models.PositiveIntegerField(default=0, verbose_name='درصد بیمه')),
                ('insurance_sent', models.BooleanField(default=False, verbose_name='ارسال شده به بیمه')),
                ('insurance_paid', models.BooleanField(default=False, verbose_name='از بیمه مبلغ دریافت شده')),
                ('is_completed', models.BooleanField(default=False, verbose_name='درمان انجام شده')),
                ('is_treatment_plan', models.BooleanField(default=False, verbose_name='طرح درمان')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('has_installment_plan', models.BooleanField(default=False, verbose_name='دارای طرح اقساط')),
                ('assistant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatments_as_assistant', to='users.profile', verbose_name='دستیار پزشک')),
                ('discount_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Patient.discounttype', verbose_name='نوع تخفیف')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatments_as_doctor', to='users.profile', verbose_name='پزشک معالج')),
                ('insurance_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Patient.insuranceprovider', verbose_name='بیمه\u200cگر')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='Patient.patientrecord', verbose_name='بیمار')),
                ('treatment_detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatments', to='Patient.treatmentdetail', verbose_name='شرح درمان')),
                ('treatment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatments', to='Patient.treatmenttype', verbose_name='نوع درمان')),
            ],
            options={
                'verbose_name': 'درمان',
                'verbose_name_plural': 'درمان\u200cها',
                'ordering': ['-treatment_date'],
            },
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='treatment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='installment_plan', to='Patient.treatment', verbose_name='درمان'),
        ),
        migrations.CreateModel(
            name='TreatmentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ')),
                ('payment_date', models.DateField(verbose_name='تاریخ پرداخت')),
                ('payment_method', models.CharField(choices=[('cash', 'نقدی'), ('card', 'کارت به کارت'), ('pos', 'کارتخوان'), ('wallet', 'کیف پول'), ('down_payment', 'پیش پرداخت'), ('installment', 'قسطی'), ('check', 'چک')], default='cash', max_length=50, verbose_name='روش پرداخت')),
                ('payment_status', models.CharField(choices=[('paid', 'پرداخت شده'), ('refunded', 'عودت داده شده'), ('pending', 'در انتظار'), ('pending', 'در انتظار وصول')], default='paid', max_length=20, verbose_name='وضعیت پرداخت')),
                ('refund_date', models.DateField(blank=True, null=True, verbose_name='تاریخ عودت')),
                ('refund_reason', models.TextField(blank=True, null=True, verbose_name='دلیل عودت')),
                ('check_date', models.DateField(blank=True, null=True, verbose_name='تاریخ چک')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('check_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره چک/صیادی')),
                ('check_issuer', models.CharField(blank=True, max_length=100, null=True, verbose_name='صادر کننده چک')),
                ('check_bank', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام بانک')),
                ('check_issue_date', models.DateField(blank=True, null=True, verbose_name='تاریخ صدور چک')),
                ('check_due_date', models.DateField(blank=True, null=True, verbose_name='تاریخ سررسید چک')),
                ('is_reminder_seen', models.BooleanField(default=False, verbose_name='یادآوری دیده شده؟')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='Patient.treatment', verbose_name='درمان')),
            ],
            options={
                'verbose_name': 'پرداخت درمان',
                'verbose_name_plural': 'پرداخت\u200cهای درمان',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.AddField(
            model_name='treatmentdetail',
            name='treatment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='Patient.treatmenttype'),
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='موجودی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='Patient.patientrecord', verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'کیف پول',
                'verbose_name_plural': 'کیف پول\u200cها',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ')),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'واریز'), ('PAYMENT', 'پرداخت درمان'), ('REFUND', 'عودت وجه'), ('TRANSFER_OUT', 'انتقال به غیر'), ('TRANSFER_IN', 'دریافت از غیر'), ('REFUND', 'عودت وجه')], max_length=20, verbose_name='نوع تراکنش')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده')),
                ('related_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_transaction', to='Patient.treatmentpayment', verbose_name='پرداخت عودت داده شده')),
                ('related_treatment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Patient.treatment', verbose_name='درمان مرتبط')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='Patient.wallet', verbose_name='کیف پول')),
            ],
            options={
                'verbose_name': 'تراکنش کیف پول',
                'verbose_name_plural': 'تراکنش\u200cهای کیف پول',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tariff_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ تعرفه')),
                ('effective_date', models.DateField(verbose_name='تاریخ اعمال')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('insurance_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='Patient.insuranceprovider', verbose_name='بیمه\u200cگر')),
                ('treatment_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_tariffs', to='Patient.treatmentdetail', verbose_name='جزئیات درمان')),
            ],
            options={
                'verbose_name': 'تعرفه بیمه',
                'verbose_name_plural': 'تعرفه\u200cهای بیمه',
                'unique_together': {('insurance_provider', 'treatment_detail')},
            },
        ),
         # اضافه کردن عملیات RunPython برای ایجاد انواع تخفیف پیش‌فرض
        migrations.RunPython(
            create_default_discount_types,
            delete_default_discount_types,
        ),
        
        # اضافه کردن عملیات RunPython برای ایجاد انواع بیمه پیش‌فرض
        migrations.RunPython(
            create_default_insurance_types,
            delete_default_insurance_types,
        ),
    ]
