# Generated by Django 5.0.14 on 2025-07-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='is_manual_price',
            field=models.BooleanField(default=False, verbose_name='قیمت دستی'),
        ),
    ]
