# Generated by Django 5.0.14 on 2025-07-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0002_treatment_is_manual_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinsurance',
            name='coverage_ceiling',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='سقف پوشش (ریال)'),
        ),
    ]
