# Generated by Django 5.0.14 on 2025-07-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0003_patientinsurance_coverage_ceiling'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinsurance',
            name='used_coverage',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='مقدار استفاده شده از بیمه (ریال)'),
        ),
    ]
