# Generated by Django 5.0.14 on 2025-07-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0004_patientinsurance_used_coverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinsurance',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
    ]
