# Generated by Django 5.0.14 on 2025-06-12 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


# تابع ایجاد یونیت‌های پیش‌فرض
def create_default_units(apps, schema_editor):
    # دریافت مدل Unit
    Unit = apps.get_model('appointments', 'Unit')
    
    # ایجاد یونیت‌های پیش‌فرض
    unit1 = Unit.objects.create(name='یونیت 1')
    unit2 = Unit.objects.create(name='یونیت 2')
    unit3 = Unit.objects.create(name='یونیت 3')


# تابع حذف یونیت‌های پیش‌فرض (برای rollback)
def delete_default_units(apps, schema_editor):
    # دریافت مدل Unit
    Unit = apps.get_model('appointments', 'Unit')
    
    # حذف یونیت‌های پیش‌فرض
    Unit.objects.filter(name__in=['یونیت 1', 'یونیت 2', 'یونیت 3']).delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedules', '0002_remove_holiday_evening_end_and_more'),
        ('users', '0006_personnelcard_card_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام یونیت')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='appointments.unit', verbose_name='یونیت والد')),
            ],
            options={
                'verbose_name': 'یونیت',
                'verbose_name_plural': 'یونیت‌ها',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام خانوادگی')),
                ('national_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد ملی')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تماس')),
                ('file_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره پرونده')),
                ('date', models.DateField(blank=True, null=True, verbose_name='تاریخ مراجعه')),
                ('time_from', models.TimeField(blank=True, null=True, verbose_name='از ساعت')),
                ('time_to', models.TimeField(blank=True, null=True, verbose_name='تا ساعت')),
                ('status', models.CharField(choices=[('normal', 'عادی'), ('emergency', 'اورژانسی'), ('pending', 'در انتظار'), ('visit', 'در حال ویزیت'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده')], default='normal', max_length=20, verbose_name='وضعیت')),
                ('visited', models.BooleanField(default=False, verbose_name='بیمار ویزیت شده')),
                ('no_file', models.BooleanField(default=False, verbose_name='بدون پرونده')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('treatment_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع درمان')),
                ('treatment_description', models.TextField(blank=True, null=True, verbose_name='شرح درمان')),
                ('referral', models.CharField(blank=True, max_length=255, null=True, verbose_name='معرف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_appointments', to='users.profile', verbose_name='پزشک')),
                ('treating_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treated_appointments', to='users.profile', verbose_name='پزشک معالج')),
                ('work_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedules.workschedule', verbose_name='برنامه کاری')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.unit', verbose_name='یونیت')),
            ],
            options={
                'verbose_name': 'نوبت',
                'verbose_name_plural': 'نوبت‌ها',
                'ordering': ['-date', 'time_from'],
            },
        ),
        
        # اضافه کردن عملیات RunPython برای ایجاد یونیت‌های پیش‌فرض
        migrations.RunPython(
            create_default_units,
            delete_default_units,
        ),
    ]
