# Generated by Django 5.0.14 on 2025-05-30 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_personnelcard_card_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان برنامه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedules', to='users.profile')),
            ],
            options={
                'verbose_name': 'برنامه کاری',
                'verbose_name_plural': 'برنامه\u200cهای کاری',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ تعطیلی')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='توضیحات')),
                ('morning_start', models.TimeField(blank=True, null=True, verbose_name='شروع شیفت صبح')),
                ('morning_end', models.TimeField(blank=True, null=True, verbose_name='پایان شیفت صبح')),
                ('evening_start', models.TimeField(blank=True, null=True, verbose_name='شروع شیفت عصر')),
                ('evening_end', models.TimeField(blank=True, null=True, verbose_name='پایان شیفت عصر')),
                ('work_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='schedules.workschedule')),
            ],
            options={
                'verbose_name': 'تعطیلی',
                'verbose_name_plural': 'تعطیلات',
                'ordering': ['date'],
                'unique_together': {('work_schedule', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DailySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'شنبه'), (1, 'یکشنبه'), (2, 'دوشنبه'), (3, 'سه\u200cشنبه'), (4, 'چهارشنبه'), (5, 'پنج\u200cشنبه'), (6, 'جمعه')], verbose_name='روز هفته')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('morning_start', models.TimeField(verbose_name='شروع شیفت صبح')),
                ('morning_end', models.TimeField(verbose_name='پایان شیفت صبح')),
                ('evening_start', models.TimeField(verbose_name='شروع شیفت عصر')),
                ('evening_end', models.TimeField(verbose_name='پایان شیفت عصر')),
                ('work_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_schedules', to='schedules.workschedule')),
            ],
            options={
                'verbose_name': 'برنامه روزانه',
                'verbose_name_plural': 'برنامه\u200cهای روزانه',
                'ordering': ['day_of_week'],
                'unique_together': {('work_schedule', 'day_of_week')},
            },
        ),
    ]
