# Generated by Django 5.0.14 on 2025-06-06 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holiday',
            name='evening_end',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='evening_start',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='morning_end',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='morning_start',
        ),
    ]
